### ISSUE TITLE
Creating a budibase plugin

### ISSUE THREAD

**Issue by JayP718** [muonw/powertable#10]
Hi,

This is awesome stuff! 

I'm looking to port this component to a low code platform called Budibase so that way it can become a plugin. Budibase is open source and I noticed this was published with an MIT License but just reaching out to get your permission before doing so :)

**Comment by muonw-public** [comment]
Thank you for your interest. As you rightly mentioned, the license certainly welcomes such distributions. Just take into account that PowerTable is still in beta.

**Comment by JayP718** [comment]
Done https://github.com/JayP718/powertable_bb_plugin ! Thank you
