### ISSUE TITLE
Package installable but not visible in NPM registry

### ISSUE THREAD

**Issue by droher** [muonw/powertable#12]
**Describe the bug**

I can successfully manually install the package using `npm`, but it's not showing up in the registry. Is it possible that the package is currently private?

**To Reproduce**
This works:
`npm i muonw/powertable`

But there are no results here (when I am both logged out and logged in):
https://www.npmjs.com/search?q=powertable

And when I add it to my `package.json` as a dependency and try to use `pnpm install` I get:
```
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@muonw%2Fpowertable: Not Found - 404

This error happened while installing a direct dependency of [app]

@muonw/powertable is not in the npm registry, or you have no permission to fetch it.
```

**Expected behavior**

Package should be visible in the registry installable via `pnpm`

**Desktop (please complete the following information):**

M1 Macbook on MacOS 13.1
npm@9.2.0
pnpm@7.19.0

**Additional context**
Thanks for making the package, excited to start using it!

**Comment by muonw-public** [comment]
Thank you for the report. This is actually the expected behavior. PowerTable is not in the npm registry at this moment. 
`npm i muonw/powertable` installs the package directly from this Github repository ([more info](https://docs.npmjs.com/cli/v9/commands/npm-install)).
