### ISSUE TITLE
[Improvement] Remove empty filters on remote data query

### ISSUE THREAD

**Issue by TheArcaneBrony** [muonw/powertable#13]
Currently, all empty filters are passed as remote parameters. This seems oddly pointless.
Would it be reasonable to filter these before calling dataFeed?
Evaluating these would inevitably make no difference on the end result anyways...

**Comment by muonw-public** [comment]
Filtering out the empty values before calling the API sounds like a good idea. The expectation is to have access to unaltered objects in dataFeed, but they can be customized by user (inside the user-defined dataFeed function) before calling the API.
