### ISSUE TITLE
Simple Row Select

### ISSUE THREAD

**Issue by kaijachmann** [muonw/powertable#18]
Hi there, 
is there a possiblity to style the last clicked row with different background? 
The use-case is quite simple: click a row, now it should be highlighted somehow (background-color would be easiest), without further checkboxes visible. 
I could image, setting the selected index via prop would be nice, too.

Any hints?

Greetz
Kai

**Comment by muonw-public** [comment]
Yes, there is a custom event that gives you the last clicked row:

https://github.com/muonw/powertable#events

Once you have the row element, you can style it using CSS.
