### ISSUE TITLE
[question] how to filter datetime data?

### ISSUE THREAD

**Issue by bokunodev** [muonw/powertable#2]
how to filter data of type datetime ? and is it possible to filter from external form  for remote data?

**Comment by muonw** [comment]
The current version (0.1.6) only supports [filtering by RegEx and string match](https://github.com/muonw/powertable/blob/624846bc6b23715d37710f9cc06a33d05172ed83/src/lib/components/PowerTable.svelte#L376). A solution would be to allow for user defined functions to handle custom filtering, sorting, etc. and then have a collection of example functions to cover the popular data types and formats.

As for the second question, yes! When displaying remote data, most computations including searching, filtering, sorting, and calculating the pagination data can only be done on the server. The relevant requests will be [sent to the server](https://github.com/muonw/powertable/blob/624846bc6b23715d37710f9cc06a33d05172ed83/src/lib/components/PowerTable.svelte#L270) automatically (e.g. when a filter phrase changes).

**Comment by muonw** [comment]
In version 0.2.4, filtering of datetime data is possible via Custom Filtering.
Here is an example: https://muonw.github.io/powertable/examples/example10
