### ISSUE TITLE
Problem installing PowerTable

### ISSUE THREAD

**Issue by haenf** [muonw/powertable#23]
Muonw, I have a problem (re)installing PowerTable. I follow the directions explained in your documentation, but I can't get it to work...

In my project map:
```
> npm config set @muonw:registry https://node.pkgreg.com/ -L project 
> npm i -D @muonw/powertable
```
This gives me the following error message:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@muonw%2fpowertable - Not found
npm ERR! 404 
npm ERR! 404  '@muonw/powertable@*' is not in this registry.
```
I tried it from the Windows Terminal as administrator and from PowerShell in VS Code on Windows 11 Pro. But no result (except the error message...). When I copy an older version to the `node_modules` map everything works fine,  but I like to use the most current version. What is going wrong?

**Comment by muonw-public** [comment]
npm is looking for the package on `registry.npmjs.org` instead of `node.pkgreg.com`. The first command you ran should have prevented this and I'm not sure why it didn't ([this post](https://stackoverflow.com/a/69324487) might help). But, as a workaround, you can try the following command:

```sh
npm i -D @muonw/powertable --@muonw:registry=https://node.pkgreg.com/
```

**Comment by haenf** [comment]
Yes, the workaround seems to work okay. Thank you for the quick replay!
