### ISSUE TITLE
Sorting is not passed to dataFeed user function & preserveFilters is not applied

### ISSUE THREAD

**Issue by randomt4sk** [muonw/powertable#25]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@muonw/powertable@0.3.2` for the project I'm working on.

When using remote data with _dataFeed_ user function, _sorting_ is not provided as argument, which makes it hard to send it to the backend.

Also _preserveFilters_ is not applied in _dataFeed's_ _initialize_ call, so _options, search & filters_ need to be manually set. I'm not sure if this is intended, but seems to add a lot of boilerplate code. Instead of manually setting it, as in my patch, it could also be fixed in _initialize_ signature (to still fallback to _preserveFilters_, even when render is _provided_).
Alternatively it could also be passed to _dataFeed_ to move the decision to user function.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@muonw/powertable/package/components/PowerTable.svelte b/node_modules/@muonw/powertable/package/components/PowerTable.svelte
index 72fb626..66c3e05 100644
--- a/node_modules/@muonw/powertable/package/components/PowerTable.svelte
+++ b/node_modules/@muonw/powertable/package/components/PowerTable.svelte
@@ -206,9 +206,10 @@ async function renderTable() {
         remoteParams['options'] = options;
         remoteParams['search'] = searchObj;
         remoteParams['filters'] = filterObj;
+        remoteParams['sorting'] = sorting;
         let newData = await options.userFunctions?.dataFeed(remoteParams);
         if (newData?.data) {
-            initialize(newData.instructs ?? [], newData.options ?? {}, newData.data, { render: false });
+            initialize(newData.instructs ?? [], newData.options ?? {}, newData.data, { render: false, preserveFilters: true });
             // Already filtered on the server
             matchedData = data;
             // Already sorted on the server
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by muonw-public** [comment]
Thank you for your solution. Your fix was applied to the new version (2.3.2).
