### ISSUE TITLE
Passing additional props to component

### ISSUE THREAD

**Issue by paulocr** [muonw/powertable#26]
Hello,

First of all thanks for the great work.
I want to ask if it's possible to pass additional props to a component. 

My use case is I want to reuse the component in other areas but I want to change the layout depending on where it's used.

I was thinking of something like this:

```
	key: 'subscriptions',
	title: 'Subscripciones',
	parseAs: 'component',
	dataComponent: TableComponent({..., additionalProp: 'table'})
```

Thanks!

**Comment by paulocr** [comment]
For my use case I thought about it a little better and I guess I can leverage rowId and rowIndex to detect when the component is being called from PowerTable but I still would be interested to know if you have any thoughts on adding additional props. Thanks!

**Comment by muonw-public** [comment]
I don't think it's feasible to pass custom props, but as you pointed out you can use `rowId` and `rowIndex` (as well as `value`) props and let your component decide what to render.

The new release (v2.3.4) also makes `instructKey` available to your component. So, if you plan to reuse your component across different columns, you can now detect the column using instructKey.

**Comment by paulocr** [comment]
Thank you!
