### ISSUE TITLE
Refreshing remote data

### ISSUE THREAD

**Issue by smashmiek** [muonw/powertable#37]
Firstly, big thanks for this library.

Is there a way to manually trigger a refresh of a remote data feed?

I have a button on each row which I'm rendering with a custom svelte component. The button triggers an API call that changes the data in the backend, but I would like to be able to reflect that change in the front-end.

I was wondering if there is any way to trigger powerTable to get new data?

Thanks

**Comment by muonw-public** [comment]
You have a component similar to this:
```svelte
<PowerTable {ptInstructs} {ptOptions} {ptData} />
```
Once you update the backend, re-fetch the new values and reassign the props (e.g. ptData = myNewData).
