### ISSUE TITLE
 parseAs: 'unsafe-html' to parse Svelte too

### ISSUE THREAD

**Issue by espansione8** [muonw/powertable#9]
**Is your feature request related to a problem? Please describe.**
can't render Svelte code for example:
`row['thisKey'] = <div on:click={onTransfer}>Transfer</div>`

`on:click` get ignored

**Describe the solution you'd like**
parse Svelte part too

**Comment by muonw-public** [comment]
Thank you for your suggestion.
For reference, this is the part of the code relevant to unsafe-html:
https://github.com/muonw/powertable/blob/11e2660784b4a950e0ea817a51159e3bb885482e/src/lib/components/PowerTable.svelte#L932
And possible solutions may involve dynamic rendering via a [helper component](https://svelte.dev/examples/svelte-component) or [slot](https://svelte.dev/tutorial/slots).

**Comment by muonw-public** [comment]
In version 2.3.0 you can use your custom Svelte component to render data, as demonstrated in the second table here:

https://muonw.github.io/muonw-powertable/examples/example2
